#!/bin/bash

## This is the rip-ninja module, a convinient wrapper for cdparanoia.
## You can use this script to rip audio from a cd and instantly convert it into any format that ffmpeg can turn a wave file into.
## Note that audio tagging does not work for every output format

MUSIC_DIR=~/Music
WAVE_DIR=$MUSIC_DIR/wav
FLAC_DIR=$MUSIC_DIR/flac

### ------------------------------------------------------------

print_help () {
	echo -e "USAGE: rip-ninja [OPTIONS]\nStill have to figure out how to do a good help page, please come back later."
}

overwrite_prompt () {
	echo -e "Warning! It seems that $1 already exists in the $MUSIC_DIR directory.\nOverwrite files? (y/n)"
	read user_input

	if [ "$user_input" != "y" ] && [ "$user_input" != "Y" ]
	then
		echo "Aborted."
		exit 1
	fi
}

## Start of the script - parsing command line arguments
## Poudly stolen from stackoverflow

UNKNOWN_OPTION=()
while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -o|--output-directory)
      OUTPUT_DIR="$2"
      shift # past argument
      shift # past value
      ;;
    -f|--format)
      FORMAT="$2"
      shift # past argument
      shift # past value
      ;;
    *)    # unknown option
      UNKNOWN_OPTION+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done

set -- "${UNKNOWN_OPTION[@]}" # restore position of unknown args array

# Ripping cd into wave files
cd $OUTPUT_DIR || exit
cdparanoia --search-for-drive --batch

# Converting ripped wave files into flacs if user passed --output-format argument
if [ ! -z $FORMAT ]
then
    for track in *;
    do
	    ffmpeg -i $track $OUTPUT_DIR/$track.$FORMAT || exit
        rm $track
    done
fi
